schema_version = "1.0.0"

id = "M8"
version = "3.6.8"
name = "M8 Toolbox"
tagline = "Efficiency is life in complex 3D modeling projects. M8 is not just a toolbox, it's the lubricant for your workflow."
maintainer = "MaobuKawaii"
type = "add-on"
license = ["SPDX:GPL-2.0-or-later"]

# 最低支持的 Blender 版本（扩展系统要求 4.2.0 起步）
blender_version_min = "4.2.0"
